# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('vat', models.FloatField(default=0.2)),
                ('limit', models.IntegerField()),
                ('multiple', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'option tarifaire',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('vat', models.FloatField(default=0.2)),
                ('limit', models.IntegerField()),
                ('required_questions', models.ManyToManyField(related_name='tickets', to='questions.Question', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'tarif',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('answers', models.ManyToManyField(related_name='tickets', to='questions.Answer', verbose_name='réponses')),
                ('options', models.ManyToManyField(related_name='tickets', to='ticketing.OptionPrice', verbose_name='tarif')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.Price', verbose_name='tarif')),
            ],
            options={
                'verbose_name': 'billet',
            },
        ),
    ]
