# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionprice',
            name='prices',
            field=models.ManyToManyField(blank=True, related_name='options', to='ticketing.Price', verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='required_questions',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='questions.Question', verbose_name='questions'),
        ),
    ]
