# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_guest'),
        ('ticketing', '0003_auto_20161201_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shop.Order', verbose_name='commande'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='questions.Answer', verbose_name='réponses'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='ticketing.OptionPrice', verbose_name='tarif'),
        ),
    ]
