# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20161202_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=0, verbose_name='nombre')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='ticketing.OptionPrice')),
            ],
            options={
                'verbose_name': "achat d'option",
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='options',
        ),
        migrations.AddField(
            model_name='optionselection',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_selection', to='ticketing.Ticket'),
        ),
    ]
