# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'réponse',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=511)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('T', 'Champ'), ('Z', 'Zone libre'), ('C', 'Case à cocher'), ('R', 'Boutton radio')], default='T', max_length=1)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'question',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='réponses', to='questions.Question'),
        ),
    ]
