# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
