version: '2'

services:
  app:
    build: .
    container_name: yevent

    # As migrate and collectstatic need configuration from this file, we can't extract them to Dockerfile
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && /usr/bin/supervisord"

    environment:
      - DJANGO_ENV=prodapp
      - DEBUG=False
      - SSL=False
      - DJANGO_LOCALE=fr-fr
      - DJANGO_TIMEZONE=Europe/Paris
      - DATABASE_URL=postgres://yevent:yevent@localhost:5432/yevent

    expose:
      - "8000"
    volumes:
      - ./static_root:/app/static_root
