# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'verbose_name': "Liste d'attente"},
        ),
        migrations.AddField(
            model_name='waitingticket',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Téléphone'),
        ),
    ]
