# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20170114_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingticket',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
