# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'En cours'), ('QUESTIONS', 'Remplis les questions'), ('PAYMENT', 'En cours de paiement'), ('WAITING_PAYMENT', 'En attente du paiement'), ('PAID', 'Payé')], max_length=15, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'commande',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('amount_off', models.FloatField(default=0)),
                ('percent_off', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'code de réduction',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.PromoCode'),
        ),
    ]
