# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0014_auto_20161201_2024'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='invitation.Guest', verbose_name='Invité'),
            preserve_default=False,
        ),
    ]
