# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CB', 'Carte bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement')], default='CB', max_length=4, verbose_name='moyen de paiement')),
                ('reference', models.CharField(blank=True, default='', max_length=255, verbose_name='référence')),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.Order')),
            ],
            options={
                'verbose_name': 'paiement',
            },
        ),
    ]
