# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nom')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.Guest', verbose_name=b'Invit\xc3\xa9 par')),
            ],
            options={
                'verbose_name': 'Invit\xe9',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yurplan_id', models.CharField(max_length=100, verbose_name=b'ID Yurplan')),
                ('seats_count', models.IntegerField(verbose_name=b'Nombre de places')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.Guest')),
            ],
            options={
                'verbose_name': 'Commande',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nom')),
                ('max_seats', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Type',
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.Type', verbose_name=b'Type'),
        ),
    ]
