# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20161121_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'invité'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'commande'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'type'},
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='invitation.Guest', verbose_name='invité par'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.Type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='invitation.Guest'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seats_count',
            field=models.IntegerField(verbose_name='nombre de places'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
    ]
