# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_auto_20161123_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='code'),
        ),
    ]
