# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_guest_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='Jean', max_length=255, verbose_name='prénom'),
            preserve_default=False,
        ),
    ]
