# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_auto_20161124_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='last_seen_at',
            field=models.DateTimeField(null=True, verbose_name='dernière visite'),
        ),
    ]
