# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import invitation.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_guest_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_seen_at',
            field=models.DateTimeField(auto_created=True, verbose_name='dernière visite'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='max_seats',
            field=models.IntegerField(default=invitation.models.Guest.type_max_seats),
        ),
    ]
