# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_auto_20161124_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='default_max_seats',
            field=models.IntegerField(default=7),
        ),
    ]
