# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_type_default_max_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='max_seats',
            field=models.IntegerField(),
        ),
    ]
