# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0012_auto_20161209_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'En cours'), (1, 'payée'), (2, 'annulée'), (3, 'annulée (délais)')], default=1, verbose_name='statut de la commande'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='email_received',
            field=models.BooleanField(default=False, verbose_name='email envoyé'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='max_seats',
            field=models.IntegerField(verbose_name='places'),
        ),
    ]
