# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_auto_20161125_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
